import React, { forwardRef } from 'react';
import {
  ChevronLeft,
  Copy,
  Check,
  RefreshCw,
  Loader2,
  ExternalLink,
  AlertTriangle,
} from 'lucide-react';
import { IconButton, SegmentedControl, StatusDot } from '../ui/index.jsx';
import NotionIcon from '../NotionIcon.jsx';
import { formatDate, formatTime } from '../../lib/format.js';
import { meetingHostname, meetingPlatform } from '../../lib/platform.js';

const STT_SERVICE_LABELS = {
  google:     'Google STT',
  sarvam:     'Sarvam AI',
  assemblyai: 'AssemblyAI',
};

const SENTIMENT_LABELS = {
  positive: 'Positive',
  neutral:  'Neutral',
  mixed:    'Mixed',
  tense:    'Tense',
};

function metaText(session, notes, durationLabel) {
  const attendees = notes?.attendees || [];
  const parts = [
    session.started_at && formatDate(session.started_at),
    session.started_at && formatTime(session.started_at),
    notes?.duration || durationLabel,
    attendees.length > 0 && `${attendees.length} attendee${attendees.length !== 1 ? 's' : ''}`,
  ].filter(Boolean);
  return parts.join(' · ');
}

function metaChips(session, notes) {
  const sentiment = SENTIMENT_LABELS[notes?.sentiment];
  const hostname = meetingHostname(session.meeting_url);
  const platform = meetingPlatform(session.meeting_url);
  const stt = notes?._sttService ? (STT_SERVICE_LABELS[notes._sttService] || notes._sttService) : null;

  const chips = [];
  if (sentiment) chips.push(<span key="sentiment" className="pill-quiet">{sentiment}</span>);
  if (notes) {
    chips.push(
      <span key="mode" className="pill-quiet">{notes._rawMarkdown ? 'Markdown' : 'JSON'}</span>
    );
  }
  if (notes?._geminiModel) {
    chips.push(
      <span key="model" className="pill-quiet" title={`Notes generated by ${notes._geminiModel}`}>
        {notes._geminiModel}
      </span>
    );
  }
  if (stt) {
    chips.push(
      <span key="stt" className="pill-quiet" title={`Transcribed with ${stt}`}>{stt}</span>
    );
  }
  if (hostname) {
    chips.push(
      <button
        key="host"
        type="button"
        className="pill-quiet hover:text-ink hover:border-ink transition-colors"
        onClick={() => window.meetmind?.shell?.openExternal(session.meeting_url)}
        title={`Open ${session.meeting_url}`}
      >
        {platform?.icon && (
          <img src={platform.icon} alt="" className="w-16 h-16 object-contain logo-mono" aria-hidden="true" />
        )}
        {hostname}
      </button>
    );
  }
  return chips;
}

// Slim sticky bar: back, view tabs and note actions on one row. The meeting
// title only appears here once the in-page title has scrolled out of view.
export function NoteToolbar({
  title,
  showTitle,
  notes,
  tabs,
  activeTab,
  onTabChange,
  onBack,
  busy,
  copied,
  onCopy,
  regenerating,
  onRegenerate,
  notionUrl,
  uploading,
  onSyncNotion,
}) {
  return (
    <header className="flex-shrink-0 border-b border-ink bg-paper">
      <div className="w-full px-24 py-8 flex items-center gap-16">
        <IconButton label="Back to meetings" onClick={onBack} className="flex-shrink-0">
          <ChevronLeft size={18} strokeWidth={1.75} />
        </IconButton>

        <p
          aria-hidden="true"
          title={title}
          className={`flex-1 min-w-0 truncate text-body-sm font-medium text-ink transition-opacity duration-150 ${
            showTitle ? 'opacity-100' : 'opacity-0'
          }`}
        >
          {title}
        </p>

        <SegmentedControl
          label="Meeting views"
          options={tabs}
          value={activeTab}
          onChange={onTabChange}
          size="sm"
        />

        {notes && (
          <div className="flex items-center gap-4 flex-shrink-0">
            <IconButton label={copied ? 'Copied' : 'Copy notes as Markdown'} onClick={onCopy}>
              {copied ? <Check size={16} strokeWidth={2} /> : <Copy size={16} strokeWidth={1.75} />}
            </IconButton>

            <IconButton
              label={regenerating ? 'Regenerating…' : 'Regenerate notes'}
              onClick={onRegenerate}
              disabled={busy || regenerating || uploading}
            >
              {regenerating
                ? <Loader2 size={16} strokeWidth={2} className="spinner" />
                : <RefreshCw size={16} strokeWidth={1.75} />}
            </IconButton>

            {notionUrl ? (
              <>
                <button
                  type="button"
                  onClick={() => window.meetmind.shell.openExternal(notionUrl)}
                  className="btn-ghost px-16 py-4 text-caption"
                  title="Open in Notion"
                >
                  <StatusDot tone="ok" />
                  <span className="hidden lg:inline">Open in Notion</span>
                  <span className="lg:hidden">Notion</span>
                  <ExternalLink size={14} strokeWidth={1.75} />
                </button>
                <IconButton
                  label={uploading ? 'Syncing to Notion…' : 'Re-sync to Notion'}
                  onClick={onSyncNotion}
                  disabled={uploading || busy}
                >
                  {uploading ? <Loader2 size={16} strokeWidth={2} className="spinner" /> : <NotionIcon size={16} />}
                </IconButton>
              </>
            ) : (
              <button
                type="button"
                onClick={onSyncNotion}
                disabled={uploading || busy}
                className="btn-ghost px-16 py-4 text-caption"
                title="Upload notes to Notion"
              >
                {uploading ? <Loader2 size={14} strokeWidth={2} className="spinner" /> : <NotionIcon size={14} />}
                {uploading ? 'Syncing…' : 'Sync to Notion'}
              </button>
            )}
          </div>
        )}
      </div>
    </header>
  );
}

// Title, meta line and chips at the top of the scrolling body, so they scroll
// away with the notes instead of permanently taking up the viewport.
export const NoteTitleBlock = forwardRef(function NoteTitleBlock(
  { session, notes, title, durationLabel, processingError },
  ref,
) {
  const meta = metaText(session, notes, durationLabel);
  const chips = metaChips(session, notes);

  return (
    <div className="pt-32 pb-8">
      <h1 ref={ref} className="text-heading font-medium text-ink break-words">{title}</h1>
      {(meta || chips.length > 0) && (
        <div className="flex items-center flex-wrap gap-8 mt-8">
          {meta && <p className="text-body-sm text-graphite mr-8">{meta}</p>}
          {chips}
        </div>
      )}
      {processingError && (
        <p role="alert" className="flex items-start gap-8 text-caption text-signal mt-16">
          <AlertTriangle size={16} strokeWidth={1.75} className="flex-shrink-0 mt-[2px]" />
          <span className="min-w-0 break-words">{processingError}</span>
        </p>
      )}
    </div>
  );
});
