import React from 'react';
import {
  ChevronLeft,
  Copy,
  Check,
  RefreshCw,
  Loader2,
  ExternalLink,
  AlertTriangle,
} from 'lucide-react';
import { IconButton, SegmentedControl, StatusDot } from '../ui/index.jsx';
import NotionIcon from '../NotionIcon.jsx';
import { formatDate, formatTime } from '../../lib/format.js';
import { meetingHostname, meetingPlatform } from '../../lib/platform.js';

const STT_SERVICE_LABELS = {
  google:     'Google STT',
  sarvam:     'Sarvam AI',
  assemblyai: 'AssemblyAI',
};

const SENTIMENT_LABELS = {
  positive: 'Positive',
  neutral:  'Neutral',
  mixed:    'Mixed',
  tense:    'Tense',
};

function MetaLine({ session, notes, durationLabel }) {
  const attendees = notes?.attendees || [];
  const parts = [
    session.started_at && formatDate(session.started_at),
    session.started_at && formatTime(session.started_at),
    notes?.duration || durationLabel,
  ].filter(Boolean);

  return (
    <p className="text-body-sm text-graphite mt-8">
      {parts.join(' · ')}
      {attendees.length > 0 && (
        <span title={attendees.join(', ')}>
          {parts.length > 0 ? ' · ' : ''}
          {attendees.length} attendee{attendees.length !== 1 ? 's' : ''}
        </span>
      )}
    </p>
  );
}

function MetaChips({ session, notes }) {
  const sentiment = SENTIMENT_LABELS[notes?.sentiment];
  const hostname = meetingHostname(session.meeting_url);
  const platform = meetingPlatform(session.meeting_url);
  const stt = notes?._sttService ? (STT_SERVICE_LABELS[notes._sttService] || notes._sttService) : null;

  const chips = [];
  if (sentiment) chips.push(<span key="sentiment" className="pill-quiet">{sentiment}</span>);
  if (notes) {
    chips.push(
      <span key="mode" className="pill-quiet">{notes._rawMarkdown ? 'Markdown' : 'JSON'}</span>
    );
  }
  if (notes?._geminiModel) {
    chips.push(
      <span key="model" className="pill-quiet" title={`Notes generated by ${notes._geminiModel}`}>
        {notes._geminiModel}
      </span>
    );
  }
  if (stt) {
    chips.push(
      <span key="stt" className="pill-quiet" title={`Transcribed with ${stt}`}>{stt}</span>
    );
  }
  if (hostname) {
    chips.push(
      <button
        key="host"
        type="button"
        className="pill-quiet hover:text-ink hover:border-ink transition-colors"
        onClick={() => window.meetmind?.shell?.openExternal(session.meeting_url)}
        title={`Open ${session.meeting_url}`}
      >
        {platform?.icon && (
          <img src={platform.icon} alt="" className="w-16 h-16 object-contain logo-mono" aria-hidden="true" />
        )}
        {hostname}
      </button>
    );
  }

  if (!chips.length) return null;
  return <div className="flex items-center flex-wrap gap-8 mt-16">{chips}</div>;
}

export default function NoteHeader({
  session,
  notes,
  title,
  durationLabel,
  tabs,
  activeTab,
  onTabChange,
  onBack,
  processingError,
  busy,
  copied,
  onCopy,
  regenerating,
  onRegenerate,
  notionUrl,
  uploading,
  onSyncNotion,
}) {
  return (
    <header className="flex-shrink-0 border-b border-ink bg-paper">
      <div className="mx-auto w-full max-w-[880px] px-32 pt-24 pb-24">
        <div className="flex items-start gap-16">
          <IconButton label="Back to meetings" onClick={onBack} className="mt-4 flex-shrink-0">
            <ChevronLeft size={18} strokeWidth={1.75} />
          </IconButton>

          <div className="flex-1 min-w-0">
            <h1 className="text-heading font-medium text-ink truncate">{title}</h1>
            <MetaLine session={session} notes={notes} durationLabel={durationLabel} />
            <MetaChips session={session} notes={notes} />
            {processingError && (
              <p role="alert" className="flex items-start gap-8 text-caption text-signal mt-16">
                <AlertTriangle size={16} strokeWidth={1.75} className="flex-shrink-0 mt-[2px]" />
                <span className="min-w-0 break-words">{processingError}</span>
              </p>
            )}
          </div>
        </div>

        <div className="flex items-center justify-between gap-16 flex-wrap mt-24">
          <SegmentedControl
            label="Meeting views"
            options={tabs}
            value={activeTab}
            onChange={onTabChange}
          />

          {notes && (
            <div className="flex items-center gap-8 flex-wrap">
              <button type="button" onClick={onCopy} className="btn-ghost btn-sm" title="Copy notes as Markdown">
                {copied ? <Check size={14} strokeWidth={2} /> : <Copy size={14} strokeWidth={1.75} />}
                {copied ? 'Copied' : 'Copy'}
              </button>

              <button
                type="button"
                onClick={onRegenerate}
                disabled={busy || regenerating || uploading}
                className="btn-ghost btn-sm"
                title="Regenerate notes from the transcript"
              >
                {regenerating
                  ? <Loader2 size={14} strokeWidth={2} className="spinner" />
                  : <RefreshCw size={14} strokeWidth={1.75} />}
                {regenerating ? 'Regenerating…' : 'Regenerate'}
              </button>

              {notionUrl ? (
                <>
                  <button
                    type="button"
                    onClick={() => window.meetmind.shell.openExternal(notionUrl)}
                    className="btn-ghost btn-sm"
                  >
                    <StatusDot tone="ok" />
                    Open in Notion
                    <ExternalLink size={14} strokeWidth={1.75} />
                  </button>
                  <IconButton
                    label={uploading ? 'Syncing to Notion…' : 'Re-sync to Notion'}
                    onClick={onSyncNotion}
                    disabled={uploading || busy}
                  >
                    {uploading ? <Loader2 size={16} strokeWidth={2} className="spinner" /> : <NotionIcon size={16} />}
                  </IconButton>
                </>
              ) : (
                <button
                  type="button"
                  onClick={onSyncNotion}
                  disabled={uploading || busy}
                  className="btn-ghost btn-sm"
                  title="Upload notes to Notion"
                >
                  {uploading ? <Loader2 size={14} strokeWidth={2} className="spinner" /> : <NotionIcon size={14} />}
                  {uploading ? 'Syncing…' : 'Sync to Notion'}
                </button>
              )}
            </div>
          )}
        </div>
      </div>
    </header>
  );
}
