import React, { forwardRef } from 'react';
import {
  ChevronLeft,
  ChevronDown,
  ExternalLink,
  Copy,
  Check,
  FileDown,
  Trash2,
  CloudUpload,
  Loader2,
  AlertTriangle,
} from 'lucide-react';
import { IconButton, SegmentedControl, Menu, MenuItem } from '../ui/index.jsx';
import NotionIcon from '../NotionIcon.jsx';
import { metaText } from './meta.js';
import { meetingHostname, meetingPlatform } from '../../lib/platform.js';
import { useApp } from '../../lib/app-context.js';
import { providerName } from '../../lib/providers.js';

const SENTIMENT_LABELS = {
  positive: 'Positive',
  neutral:  'Neutral',
  mixed:    'Mixed',
  tense:    'Tense',
};

// Actions below read the saved notes, so they pause while there are unsaved edits.
const EDITING_HINT = 'Save or discard your edits first';

function editedLabel(iso) {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? 'Edited' : `Edited ${d.toLocaleString()}`;
}

function metaChips(session, notes, providers) {
  const sentiment = SENTIMENT_LABELS[notes?.sentiment];
  const hostname = meetingHostname(session.meeting_url);
  const platform = meetingPlatform(session.meeting_url);
  const stt = notes?._sttService && notes._sttService !== 'none' ? providerName(providers, 'stt', notes._sttService) : null;
  const llmModel = notes?._llmModel || notes?._geminiModel;

  const chips = [];
  if (sentiment) chips.push(<span key="sentiment" className="pill-quiet">{sentiment}</span>);
  if (notes) {
    chips.push(
      <span key="mode" className="pill-quiet">{notes._rawMarkdown ? 'Markdown' : 'JSON'}</span>
    );
    if (notes._editedAt) {
      chips.push(
        <span key="edited" className="pill-quiet" title={editedLabel(notes._editedAt)}>Edited</span>
      );
    }
  }
  if (llmModel) {
    const llm = notes?._llmProvider ? providerName(providers, 'llm', notes._llmProvider) : '';
    chips.push(
      <span key="model" className="pill-quiet" title={`Notes generated by ${llm ? `${llm} · ` : ''}${llmModel}`}>
        {llmModel}
      </span>
    );
  }
  if (stt) {
    chips.push(
      <span key="stt" className="pill-quiet" title={`Transcribed with ${stt}${notes?._sttModel ? ` · ${notes._sttModel}` : ''}`}>{stt}</span>
    );
  }
  if (hostname) {
    chips.push(
      <button
        key="host"
        type="button"
        className="pill-quiet hover:text-ink hover:border-ink transition-colors"
        onClick={() => window.meetmind?.shell?.openExternal(session.meeting_url)}
        title={`Open ${session.meeting_url}`}
      >
        {platform?.icon && (
          <img src={platform.icon} alt="" className="w-16 h-16 object-contain logo-mono" aria-hidden="true" />
        )}
        {hostname}
      </button>
    );
  }
  return chips;
}

// A single "Notion" button for a meeting that already has a page; it opens a small menu with
// the two things you can do with that page: open it, or replace it with the current notes.
function NotionMenu({ notionUrl, uploading, updateDisabled, updateTitle, onUpdate }) {
  return (
    <Menu
      label="Notion page"
      trigger={({ open, ...props }) => (
        <button
          type="button"
          {...props}
          disabled={uploading}
          title={uploading ? 'Updating the Notion page…' : 'Notion page'}
          className="btn-ghost px-16 py-4 text-caption"
        >
          {uploading ? <Loader2 size={14} strokeWidth={2} className="spinner" /> : <NotionIcon size={14} />}
          {uploading ? 'Updating…' : 'Notion'}
          <ChevronDown
            size={14}
            strokeWidth={1.75}
            aria-hidden="true"
            className={`transition-transform duration-150 ${open ? 'rotate-180' : ''}`}
          />
        </button>
      )}
    >
      <MenuItem
        icon={<ExternalLink size={14} strokeWidth={1.75} aria-hidden="true" />}
        onSelect={() => window.meetmind.shell.openExternal(notionUrl)}
      >
        Open in Notion
      </MenuItem>
      <MenuItem
        icon={<CloudUpload size={14} strokeWidth={1.75} aria-hidden="true" />}
        onSelect={onUpdate}
        disabled={updateDisabled}
        title={updateTitle}
      >
        Update page
      </MenuItem>
    </Menu>
  );
}

// Slim sticky bar: back, view tabs and note actions on one row. The meeting
// title only appears here once the in-page title has scrolled out of view.
// A 1fr/auto/1fr grid keeps the tabs centred on the bar whatever the widths of
// the side columns (title visibility, Notion state, notes missing); the actions
// column never shrinks below its content, so at narrow widths the tabs shift left
// instead of being overlapped.
export function NoteToolbar({
  title,
  showTitle,
  notes,
  tabs,
  activeTab,
  onTabChange,
  onBack,
  busy,
  copied,
  onCopy,
  regenerating,
  regenerate,
  exporting,
  onExportPdf,
  notionUrl,
  uploading,
  onSyncNotion,
  editing,
  onDelete,
  deleting,
}) {
  const lockTitle = editing ? { title: EDITING_HINT } : {};
  return (
    <header className="relative z-20 flex-shrink-0 border-b border-ink bg-paper">
      <div className="w-full px-24 py-8 grid grid-cols-[minmax(0,1fr)_auto_minmax(max-content,1fr)] items-center gap-16">
        <div className="flex items-center gap-16 min-w-0">
          <IconButton label="Back to meetings" onClick={onBack} className="flex-shrink-0">
            <ChevronLeft size={18} strokeWidth={1.75} />
          </IconButton>

          <p
            aria-hidden="true"
            title={title}
            className={`flex-1 min-w-0 truncate text-body-sm font-medium text-ink transition-opacity duration-150 ${
              showTitle ? 'opacity-100' : 'opacity-0'
            }`}
          >
            {title}
          </p>
        </div>

        <SegmentedControl
          label="Meeting views"
          options={tabs}
          value={activeTab}
          onChange={onTabChange}
          size="sm"
        />

        <div className="flex items-center justify-end gap-4 min-w-0">
          {notes && (
            <>
              <IconButton
                label={copied ? 'Copied' : 'Copy notes as Markdown'}
                onClick={onCopy}
                disabled={editing}
                {...lockTitle}
              >
                {copied ? <Check size={16} strokeWidth={2} /> : <Copy size={16} strokeWidth={1.75} />}
              </IconButton>

              <IconButton
                label={exporting ? 'Exporting PDF…' : 'Export as PDF'}
                onClick={onExportPdf}
                disabled={editing || exporting}
                {...lockTitle}
              >
                {exporting
                  ? <Loader2 size={16} strokeWidth={2} className="spinner" />
                  : <FileDown size={16} strokeWidth={1.75} />}
              </IconButton>

              {/* Labelled, with an icon per action, because what it regenerates follows the tab.
                  Below lg the label hides and the icon alone tells the two apart. */}
              <button
                type="button"
                onClick={regenerate.onClick}
                disabled={editing || busy || regenerating || uploading || !!regenerate.unavailable}
                aria-label={regenerating ? 'Regenerating…' : regenerate.title || regenerate.label}
                title={editing ? EDITING_HINT : regenerate.unavailable || regenerate.title || regenerate.label}
                className="btn-ghost px-8 py-4 text-caption lg:px-16 mr-4"
              >
                {regenerating ? (
                  <Loader2 size={14} strokeWidth={2} className="spinner" />
                ) : (
                  <regenerate.icon key={`icon-${regenerate.title || regenerate.label}`} size={14} strokeWidth={1.75} className="fade-in" aria-hidden="true" />
                )}
                <span key={`label-${regenerate.label}`} className="hidden lg:inline fade-in">
                  {regenerating ? 'Regenerating…' : regenerate.label}
                </span>
              </button>

              {notionUrl ? (
                <NotionMenu
                  notionUrl={notionUrl}
                  uploading={uploading}
                  updateDisabled={editing || uploading || busy}
                  updateTitle={editing ? EDITING_HINT : 'Replace the Notion page with the current notes'}
                  onUpdate={onSyncNotion}
                />
              ) : (
                <button
                  type="button"
                  onClick={onSyncNotion}
                  disabled={editing || uploading || busy}
                  className="btn-ghost px-16 py-4 text-caption"
                  title={editing ? EDITING_HINT : 'Upload notes to Notion'}
                >
                  {uploading ? <Loader2 size={14} strokeWidth={2} className="spinner" /> : <NotionIcon size={14} />}
                  {uploading ? 'Syncing…' : 'Sync to Notion'}
                </button>
              )}
            </>
          )}

          {/* Always available, including for failed or still-processing meetings that have no notes. */}
          <IconButton
            label={deleting ? 'Deleting meeting…' : 'Delete meeting'}
            onClick={onDelete}
            disabled={deleting || uploading}
            className="hover:text-signal hover:border-signal"
          >
            {deleting
              ? <Loader2 size={16} strokeWidth={1.75} className="spinner" />
              : <Trash2 size={16} strokeWidth={1.75} />}
          </IconButton>
        </div>
      </div>
    </header>
  );
}

// Title, meta line and chips at the top of the scrolling body, so they scroll
// away with the notes instead of permanently taking up the viewport.
export const NoteTitleBlock = forwardRef(function NoteTitleBlock(
  { session, notes, title, durationLabel, processingError, aside },
  ref,
) {
  const meta = metaText(session, notes, durationLabel);
  const { providers } = useApp();
  const chips = metaChips(session, notes, providers);

  return (
    <div className="pt-32 pb-8">
      <div className="flex items-start justify-between gap-16">
        <h1 ref={ref} className="min-w-0 text-heading font-medium text-ink break-words">{title}</h1>
        {aside && <div className="flex-shrink-0 mt-4">{aside}</div>}
      </div>
      {(meta || chips.length > 0) && (
        <div className="flex items-center flex-wrap gap-8 mt-8">
          {meta && <p className="text-body-sm text-graphite mr-8">{meta}</p>}
          {chips}
        </div>
      )}
      {processingError && (
        <p role="alert" className="flex items-start gap-8 text-caption text-signal mt-16">
          <AlertTriangle size={16} strokeWidth={1.75} className="flex-shrink-0 mt-[2px]" />
          <span className="min-w-0 break-words">{processingError}</span>
        </p>
      )}
    </div>
  );
});
